#!/bin/bash
# tmux create new session

path=$(
  find -L "$PWD" ~/Projects -mindepth 1 -maxdepth 4 -type d -not -path '*/.*' |
    fzf --print-query
)
path=$(echo "$path" | tail -n +2)

name=$(basename "$path")

if ! tmux has-session -t="$name"; then
  tmux new-session -s "$name" -c "$path" -d
fi

tmux switch-client -t "$name"
