#!/bin/bash

path=$(
  find -L ~/Documents ~/Projects -mindepth 1 -maxdepth 4 -type d |
    fzf --print-query
)

name=$(basename "$path")

if [[ $path == '>'* ]]; then
  # create new project
  path=~/Projects/$(echo $path | tr -d '>')
  name=$(basename "$path")
  mkdir "$path"
elif [[ $path == '<'* ]]; then
  # create new sesion with <name, given, let user select folder form pwd
  name=$(echo "$path" | tr -d '<')

else
  path=$(echo "$path" | tail -n +2)
fi

if ! tmux has-session -t="$name"; then
  tmux new-session -s "$name" -c "$path" -d
fi

tmux switch-client -t "$name"
