#!/usr/bin/zsh

alias wt="ps -x | grep waydroid"
alias ws="sudo waydroid session stop && sudo systemctl stop waydroid-container.service"
alias wr="sudo waydroid session stop && sudo systemctl restart waydroid-container.service"

alias ta="tmux attach"

alias kd='kitty --detach "$PWD"'

alias tn='nvim ~/Documents/"$(date +%F)".md'
alias e='nvim .'

################################################################################

# mkself
function note() {
  d=$(date +%F)
  file=$HOME/Projects/mkself/daily-logs/2024/$d.md
  time=$(date +%H:%M" "%p)
  head="---\nauthor: Dnyaneshwar\ndate: $d\ntags:\n  - six\n---\n\n**$time**\n"

  if [ -f "$file" ]; then
    echo "\n---\n**$time**\n" >> "$file"
  else
    echo "$head" > "$file"
  fi

  nvim "$file"
}

