#!/usr/bin/zsh

export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#ff7b72 \
--color=fg:#cdd6f4,header:#ff7b72,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#ff7b72 \
--color=border:#b4befe \
--layout=reverse --border=sharp \
--height=15"

# man

export LESS_TERMCAP_mb="$(printf "\e[1;31m")" 
export LESS_TERMCAP_md="$(printf "\e[1;31m")" 
export LESS_TERMCAP_me="$(printf "\e[0m")" 
export LESS_TERMCAP_se="$(printf "\e[0m")"
export LESS_TERMCAP_so="$(printf "\e[1;4;34m")" 
export LESS_TERMCAP_ue="$(printf "\e[0m")" 
export LESS_TERMCAP_us="$(printf "\e[1;32m")" 
#

