#!/usr/bin/zsh

export ZSH="$HOME/.oh-my-zsh"

plugins=( 
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
)

source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

################################################################################

export PATH="$HOME/.local/bin/:$PATH"
export PATH="$HOME/.cargo/bin/:$PATH"
export PATH="$HOME/.local/share/dny4/scripts/:$PATH"

################################################################################

if command -v mise &> /dev/null; then
  eval "$(mise activate zsh)"
fi

source $HOME/.local/share/dny4/zsh/aliases
source $HOME/.local/share/dny4/zsh/colors
source $HOME/.local/share/dny4/zsh/shell
source $HOME/.local/share/dny4/zsh/prompt
source $HOME/.local/share/dny4/zsh/tmux
source $HOME/.local/share/dny4/zsh/keybindings
